### ISSUE TITLE
Principle #8 – HTTP Status Codes 

### ISSUE THREAD

**Issue by cmheazel** [opengeospatial/OGC-Web-API-Guidelines#10]
• More then 70 HTTP status codes exist (summary in RFC 7231)
• You should reduce to the most important once
• Option Set #1 – Basic set        Option Set #2 – Additional
– 200 – OK                                 – 201 – Created
------------                                – 304 – Not Modified
– 400 – Bad Request                 – 401 – Unauthorized
------------                               – 403 – Forbidden
------------                               – 404 – Not Found
------------                               – 405 – Method Not Allowed
------------                               – 409 – Conflict
------------                               – 410 – Gone
------------                               – 412 – Precondition Failed
– 500 – Internal Server Error      – 503 – Service Unavailable

**Comment by ghobona** [comment]
"Principle #8 - HTTP Status Codes" should include HTTP status code 302 in Option Set 2. 
HTTP status code 302 is used by opengis.net to support persistence in URIs (through redirection).

**Comment by lvdbrink** [comment]
Dutch govt API strategy also mentions
204 No Content (response to a succesful request which results in a response without contents, e.g. a DELETE. 
406 Not Acceptable (when requested format is not supported, part of conneg)
415 Unsupported Media Type (when media type is incorrect)
422 Unprocessable Entity (when request body is correct but server is unable to comply)
429 Too Many Requests (when exceeding limit of nr of requests in a time period)

**Comment by securedimensions** [comment]
now addressed in master
