### ISSUE TITLE
Principle #9 – Use of HTTP Header

### ISSUE THREAD

**Issue by cmheazel** [opengeospatial/OGC-Web-API-Guidelines#11]
• Used to provide information that *does not* change the logic of the API
– e.g. HTTP Authorization
• Keep in mind that not all JS-API support adding “stuff” into the HTTP request header!
– e.g. Leaflet JS Library
• For Web-Applications use of “non-default” headers has performance pushback for cross-domain requests
– e.g. HTTP Authorization header on a cross-domain request causes execution of CORS (W3C Recommendation) => Pre-flight request…

**Comment by cportele** [comment]
> HTTP Header is used to provide information that does not change the logic of the API

What is the "logic of the API"? Which effects of a header change the "logic"?

**Comment by securedimensions** [comment]
how logic of HTTP headers can be overwritten to change the logic of the API is now addressed in master
