### ISSUE TITLE
Pagination

### ISSUE THREAD

**Issue by cmheazel** [opengeospatial/OGC-Web-API-Guidelines#12]
• Use limit and offset as query string parameters is common sense
– e.g. /v1/features/highways?limit=50&offset=100
• You must return metadata with each response providing the total number of resources available
– e.g. total
• As an alternative to application processing the response, you should try to use Web Linking (RFC 5988)
– Use HTTP Response Header to provide URLs for fetching the next / previous page
– This approach is application neutral and should be provided by the API as the default

**Comment by cportele** [comment]
Here is what was discussed and decided in WFS 3.0 (not limited to `Link` headers): https://github.com/opengeospatial/WFS_FES/issues/8 

> The API must return metadata with each response providing the total number of resources available (e.g. total) in the payload.

This is not always reasonable, eg when streaming is used. Please remove. What is essential is to have link to the next page.

**Comment by m-mohr** [comment]
I support what Clemens said and I think the only parameter one should standardize is the number of requested elements (limit). The way of pagination (by offset, by page number, ...) should be open to the implementation and be communicated just as links to the previous / next page.

**Comment by lvdbrink** [comment]
Dutch govt API strategy refers explicitly to HAL for pagination. It is a bit more explanatory and might be incorporated here as well. 

See https://geonovum.github.io/KP-APIs/#paginering (Dutch text, but google translate does a good job on translating this to English).

**Comment by securedimensions** [comment]
current version of master does not address the use of HAL

**Comment by hylkevds** [comment]
Note that returning counts for queries can be extremely computationally expensive in many cases and can cause queries to take a very long time to return. If someone only wants to get the first item of a certain query and is not interested in the count, making him wait because calculating the count takes ages is not nice.

In the SensorThings API you can therefore request a count with `$count=true`, and explicitly omit the count with `$count=false`. This is a standard OData parameter.

**Comment by ghobona** [comment]
The following references suggest that HAL expired without being adopted as an IETF standard.

https://datatracker.ietf.org/doc/draft-kelly-json-hal/

https://tools.ietf.org/html/draft-kelly-json-hal-06

https://groups.google.com/forum/#!topic/hal-discuss/On5ZZkNg9oA

Is it back in consideration at IETF?

**Comment by lvdbrink** [comment]
This is worth finding out! We recently had a discussion in the context of the Dutch govt API strategy about whether or not to use HAL, because of its being expired. Our backup plan is to adopt the part of HAL we want by copying it into our API strategy.

**Comment by akuckartz** [comment]
@securedimensions How was this issue resolved?

**Comment by securedimensions** [comment]
Andreas,

 

we have our next meeting this Friday and your inquiry is on the agenda.

 

Please feel free to reopen the issue so that we can respond properly…

 

Best

Andreas

**Comment by joanma747** [comment]
The principle starts with:

"APIs for large data collections should support pagination."

 I would like to propose to change it to:
"Resources that enumerate large data collections should support pagination"

The reason: Include the "enumerate" here is to knowledge that there are other means to discover resources: discover by query or templated resources that does not provide enumeration capabilities such as tiles.

I wonder if it could be useful also to mention the other alternatives for discovery of resources.
