### ISSUE TITLE
Principle 17 - Use Well-Known URL Templates and Access Paths

### ISSUE THREAD

**Issue by cmheazel** [opengeospatial/OGC-Web-API-Guidelines#19]
An additional principle from the Testbed 12 Rest User Guide

**Comment by cmheazel** [comment]
This principle calls for uniformity on how OGC API URLs are structured.  Starting with a URL template, what are the rules for:
 - Protocol (http, https, file, etc.)
 - Authority (DNS name)
 - Path (identifies the resource type)  
 - Query (selects the resources) 

Some of the Principles deal with parts of the issue, but none address the elephant as a whole.

#3 #5 #7 #8 #14 #15

**Comment by joanma747** [comment]
I have merged this principle with Principle #3b also discussed in issue #5

**Comment by securedimensions** [comment]
now addressed in master
