### ISSUE TITLE
OGC Web API Design Principles

### ISSUE THREAD

**Issue by cmheazel** [opengeospatial/OGC-Web-API-Guidelines#2]
This issue is for the general discussion of the OGC Design Principles

**Comment by cmheazel** [comment]
RE: Secure Dimensions - I have no objection to giving credit to sources, but we should include all sources.  The TB-12 REST Users Guide in particular provides content to both this resource and to the OGC Web Design Principles presentation.

**Comment by cmheazel** [comment]
Here is another example.  It's interesting how often the same principles come up.
[Hackernoon Blog entry on API design](https://hackernoon.com/restful-api-design-step-by-step-guide-2f2c9f9fcdbf)

**Comment by securedimensions** [comment]
going forward we should open new issues for new discussion topics
