### ISSUE TITLE
Addition of HTTP status code 302 to Option Set 2 in Principle #8 - HTTP Status Codes

### ISSUE THREAD

**Issue by ghobona** [opengeospatial/OGC-Web-API-Guidelines#21]
Should include HTTP status code 302 in Option Set #2. 

302 is used by opengis.net to support persistence in URIs (through redirection).

**Comment by fterpstra** [comment]
This issue is addressed by the sentence "Be explicit which 30x status codes your API supports. For any supported 30x follow the HTTP semantics." in principle #8. The table provides examples. We will integrate parts of Jeffs pull request to clarify the principle.
