### ISSUE TITLE
Plurals to return collections in Principle #5 – Don’t mix Singular and Plural

### ISSUE THREAD

**Issue by ghobona** [opengeospatial/OGC-Web-API-Guidelines#22]
This principle should include the following “Use Plurals to return collections of resources and Singular to return a single instance”. 

This was demonstrated to work well in Testbed-12. Have a look at the “Resources Summary” section of OGC 16-59 http://docs.opengeospatial.org/per/16-059.html#_resources_summary

**Comment by securedimensions** [comment]
now addressed in master
