### ISSUE TITLE
Principle 19 - Make use of geospatial relations

### ISSUE THREAD

**Issue by joanma747** [opengeospatial/OGC-Web-API-Guidelines#23]
There is something about geospatial that make it intrinsically NOT related with hypertext: georeference and geospatial relations:
Given a coverage cell, there is always a cell immediately to the East, another immediately to the North, another immediately to the South, another immediately to the West. This is a geospatial relation. Geospatial relations are so abundant in a coverage that will be very very inefficient to explicitly state then in hypertext. Relations are embedded in the coverage model (some of them could be made a bit more explicit in URL templates, but it should not be necessary). A WCS client need to be aware or spatial relations. That is not REST (in the sense that they are not explicit in hypermedia but there is nothing we can do about. Actually, spatial relations are a good thing!!.

My proposal is adding that geospatial relations that are intrinsic to the model should not be made explicit as hypertext. A client should be aware of spacial relations on the data model. In some cases could make some of them explicit in a single URL template by following some patters such as the ones used in WMTS and tilerow and tilecol.

**Comment by cmheazel** [comment]
I think the question of resources deserves a section of its' own.  
One realization that came out of Testbed 12 was that you cannot build solid RESTful services without first understanding the Resources that are being exposed.  That includes structure, taxonomy, and use.  Furthermore, resources will often be exposed through multiple service types, RESTful and non-Restful.  So you cannot impose a HATEAOS model on them.  This is particularly true of spatial-temporal resources.  

I suggest that we have a principle number 1, understand your resources.  Then reference another discussion on Resource Principles, perhaps combining with the JSON Best Practices guidance.

**Comment by joanma747** [comment]
I agree with @cmheazel on the need for a principle that identify resource types (and relations). Principle #3a - Use Well-Known Resource Classes Principle has been added. It is discussed in issue #18.

**Comment by lvdbrink** [comment]
"Make use of geospatial relations" is a good principle but we should also state that in some cases it is a good idea to make relations explicit even though they can be calculated based on geometry. 

[SDWBP 10][1] says: 

> Spatial relationships can often be derived mathematically based on geometry - but this can be computationally expensive. Topological relationships such as these can be asserted, thereby removing the need to do geometry-based calculations. A useful secondary benefit is that these relationships are easier for humans to understand!

Explicit linking also helps discovery of resources. 

In the SDWWG we talked about registering a set of topological relation types (the Simple Features DE-9IM ones) at IANA. I don't think we ever got around to doing that. This might still be a good idea.

[1]: https://www.w3.org/TR/sdw-bp/#entity-level-links

**Comment by securedimensions** [comment]
continuing in issue #36. Rest now addressed in master
