### ISSUE TITLE
Principle 17b - Use OGC services reserved URIs

### ISSUE THREAD

**Issue by joanma747** [opengeospatial/OGC-Web-API-Guidelines#24]
Should we reserve some paths for some "Common" cases and special meanings?. Can this be and added principle?

For example:
/api 
/conformance 
/collections 
/metadata

**Comment by cmheazel** [comment]
This is similar to issue #19 (Master branch Principle 17).  There should be "standard" paths and path templates which are used by all services. This will give OGC services a common look and feel.  Note that the Secure Dimensions branch interprets Principle  17 to mean something very different.

**Comment by joanma747** [comment]
Ok, I have added this list of possible OGC well knwon URIs to principle 17 to start the discussion about them.

**Comment by securedimensions** [comment]
this does belong to discussions on "building blocks" and "common elements" but not in the guidelines
