### ISSUE TITLE
Consolidate the SecureDimensions branch in the master. Focus on WebAPI or in RESTful resources?

### ISSUE THREAD

**Issue by joanma747** [opengeospatial/OGC-Web-API-Guidelines#25]
I believe we need converge on a single document for the discussion in September. I believe there are significant contributions in the SecureDimensions branch that can be incorporated in the master. 

The main difference I see is that the "master" is more focused on RESTful resources and the "SecureDimensions" branch more on WebAPI. I believe we need to avoid falling into REST and non-REST discussion again so I personally recommend to remove all reference to REST. This does not preclude that a good WebAPI should consider an analysis of the "resources" it considers and a clear separation between a requesting a resource and the response of the "filter" on a resource (that is not necessarily a resource but is a perfectly acceptable beast).

How can we get back to a single master branch by incorporating what is great from the "SecureDimensions" branch in the master that needs to be the "everybody's" branch?

**Comment by cmheazel** [comment]
I disagree with Principles 17 and 18 as modified in the Secure Dimensions branch.  The updates miss the point these Principles are trying to make (see #19 and #20).  Beyond than, I support merging into a single branch.

**Comment by cmheazel** [comment]
I'm happy to purge the word REST from the OGC vocabulary.  But we do need a way to distinguish resource-oriented architecture patterns from service-oriented architecture patterns.  Perhaps we should adopt the ROA vs SOA terminology.  OpenAPI becomes a "standard" for describing ROA APIs.  

Then we can consider two Guidance documents:
1) API Guidance (based on OpenAPI)
2) Resource Guidance (including standards for the path templates and encodings)

**Comment by joanma747** [comment]
I fully agree with the use of ROA style that we inaugurated in the WMTS 1.0 standard in the Valencia's TC. To me ROA has no definition problem.

I'm not sure if we will be able to separate API Guidance and Resource Guidance since both relay on the need to defined resources and URL templates but that is possible way forward.

Please tell us how to improve principle 17 and 18 in the right direction. I have modified 17 already.

**Comment by securedimensions** [comment]
we believe this is now addressed in master
