### ISSUE TITLE
Principle #17a - Use IANA well-known identifiers

### ISSUE THREAD

**Issue by joanma747** [opengeospatial/OGC-Web-API-Guidelines#27]
I need more details to understand the intention of this principle.  Could you provide more details. In particular I do not understand the reference to IANA. Lets continue discussing.

**Comment by securedimensions** [comment]
When designing Web-APIs, it is important to max reuse of pre-defined "well-known" identifiers (URIs). 
IANA maintains a registration system for various topics including HTTP related identifiers: https://www.iana.org/protocols

So for example, if you design an API and you want to apply authentication to the site, you may wonder if there are pre-defined authentication schemes that you could re-use. Yes, there are here (HTTP Authentication Schemes): https://www.iana.org/assignments/http-authschemes/http-authschemes.xhtml#authschemes

Or you wonder what is the mime-type for a GeoXACML policy? Answer: https://www.iana.org/assignments/media-types/media-types.xhtml => 

geoxacml+xml | application/geoxacml+xml | [OGC][Scott_Simmons]

Does this clear things?


So the principle targets to make sure that designers first look at the IANA registration system.

**Comment by joanma747** [comment]
ok... but are this things well knows URIs or well know mime-types (formats)?. 

application/geoxacml+xml | is a mime type

I have checked the URI RFC 3986 and a mime type is not a URI.
I'm still a bit confused here. Sorry.

Joan 
________________________________________
De: securedimensions <notifications@github.com>
Enviat el: diumenge, 9 de setembre de 2018 18:20
Per a: opengeospatial/OGC-Web-API-Guidelines
A/c: Joan Masó Pau; Author
Tema: Re: [opengeospatial/OGC-Web-API-Guidelines] Principle #17 - Use Well-Known URIs (#27)

When designing Web-APIs, it is important to max reuse of pre-defined "well-known" identifiers (URIs).
IANA maintains a registration system for various topics including HTTP related identifiers: https://www.iana.org/protocols

So for example, if you design an API and you want to apply authentication to the site, you may wonder if there are pre-defined authentication schemes that you could re-use. Yes, there are here (HTTP Authentication Schemes): https://www.iana.org/assignments/http-authschemes/http-authschemes.xhtml#authschemes

Or you wonder what is the mime-type for a GeoXACML policy? Answer: https://www.iana.org/assignments/media-types/media-types.xhtml =>

geoxacml+xml | application/geoxacml+xml | [OGC][Scott_Simmons]

Does this clear things?

So the principle targets to make sure that designers first look at the IANA registration system.

**Comment by securedimensions** [comment]
I think the confusion can be solved with changing the Principle to "Use IANA well-known identifiers" from https://www.iana.org/protocols
?

**Comment by joanma747** [comment]
That clarifies the issue. I have includes some clarifications in the document and I have divided principle 17 in 17a for this and 17b for the URI that OGC can reserve for all services to deal with the in a common way

**Comment by joanma747** [comment]
It helps. Thanks.
________________________________________
De: securedimensions <notifications@github.com>
Enviat el: diumenge, 9 de setembre de 2018 18:44
Per a: opengeospatial/OGC-Web-API-Guidelines
A/c: Joan Masó Pau; Author
Tema: Re: [opengeospatial/OGC-Web-API-Guidelines] Principle #17 - Use Well-Known URIs (#27)

I think the confusion can be solved with changing the Principle to "Use IANA well-known identifiers" from https://www.iana.org/protocols
?

**Comment by cportele** [comment]
https://www.iana.org/assignments/link-relations/link-relations.xml is missing from this list.

**Comment by securedimensions** [comment]
now addressed in master
