### ISSUE TITLE
Don’t Reinvent

### ISSUE THREAD

**Issue by cmheazel** [opengeospatial/OGC-Web-API-Guidelines#3]
• Aspects that are already solved in main-stream IT, simply adopt
• Just domain specific aspects – And that will be a lot…

**Comment by hylkevds** [comment]
Something that fits here: If you already have a data model, first check if existing API standards (such as OData) can be applied to it. Then you don't need to design an API at all, it follows from the model and the API standard.
The SensorThings API is an example of this.
