### ISSUE TITLE
"OGC Web API" is misleading

### ISSUE THREAD

**Issue by cportele** [opengeospatial/OGC-Web-API-Guidelines#30]
The idea should be to specify OGC API elements or building blocks that can be used in APIs, not to define a "OGC Web API".

**Comment by ghobona** [comment]
The word 'Guidelines' in the title 'OGC-Web-API-Guidelines' was supposed to reflect that this is not a specification of an OGC Web API but a set of principles to consider and abide by (if possible) when defining an OGC Web API.

**Comment by cportele** [comment]
@ghobona - That was the point, I do not think that OGC should be defining "OGC Web APIs". We should specify OGC Web API elements or building blocks that organisations can use in their APIs.

If an organisation wants to publish an API that is just build from API elements from OGC standards - fine. But we should not imply that this is the only or recommended approach.

**Comment by securedimensions** [comment]
now addressed in master
