### ISSUE TITLE
Tiles are not always equally divided. Therefore, it is not always assigned to a simple matrix.

### ISSUE THREAD

**Issue by satakagi** [opengeospatial/OGC-Web-API-Guidelines#32]
Equally divided tiling (regular tiling scheme) is treated like an implicit common sense in the geo community, but it seems to keep his eyes away from its issues. Especially in vector tiling, the issue is serious.

We have already faced issues of equally divided tiling practically over 10 years ago.
The problem is described in this slide *1.

For that reason, we implemented unequaled tiling *2 and have been practically used for many years, and  have also done that standardization *3.
In OGC's Vector Tiling Report *4, 6.4.3., There is a slight mention on non-equal tiling, but ignored without exploring that problem. I sent comments on this to contact point, but I could not get a reasonable response.

I think that geo-community should face these issues of equal divided tiling soon.

* 1: Quad Tree Composite Tiling: https://www.slideshare.net/totipalmate/quad-tree-composite-tiling-in-english
* 2: SVGMap (Open Source Implementations) http://svgmap.org/
* 3: Japan Industrial Standard (JIS): X.7197: http://www.jisc.go.jp/policy/nenji/Japans_Standardization_Policy_2013.pdf
* 4: http://docs.opengeospatial.org/per/17-041.html

**Comment by securedimensions** [comment]
this looks like the definition of a building block and so does not belong into the guidelines

**Comment by satakagi** [comment]
I do not know where your building block is being discussed. Please tell me which reference points I can participate in the discussion.

At least, the OGC Vector Tiling Report team seems to be unresponsive.

**Comment by jerstlouis** [comment]
@satakagi the latest Tile Matrix Set 1.0 will supports variable width tiles.
