### ISSUE TITLE
Register geospatial relation types in the IANA register

### ISSUE THREAD

**Issue by cportele** [opengeospatial/OGC-Web-API-Guidelines#36]
see Linda's comment in #23

**Comment by jyutzler** [comment]
Here's the actual comment: https://github.com/opengeospatial/OGC-Web-API-Guidelines/issues/23#issuecomment-458933101

**Comment by fterpstra** [comment]
Principle #16 already requires relations registered at IANA. In practice IANA does not always want to register our relations. So a fallback option is to register with the OGC Definition server. we will add this to principle #16.
