### ISSUE TITLE
Ensure discover resources mechanism.

### ISSUE THREAD

**Issue by joanma747** [opengeospatial/OGC-Web-API-Guidelines#38]
In you API, is it possible to the "follow the links" approach and discover all the resources (this is how the web works). The second possibility is provide a way to enumerate resources based on URI templates (e.g, \collections will enumerate the collectionId's in as a response).

It is a good practice to provide enumerations but there are some cases where only a lower and upper limit for an incremental consecutive number is fine, like in WMTS URL templates. 

In any case the client should be able to figure our all the resource url's by finding them explicitly, asking for them or knowing a rule to generate them.

Is it worth to have a principle for a good API?

**Comment by jyutzler** [comment]
In my view, the answer is unequivocally YES. How about this:

### Principle #XX – Make resources discoverable
When a resource has other resources associated with it, make the associated resources discoverable through _links_ in the document for that resource. For JSON documents, populate a `links` element and use [link relations](https://www.iana.org/assignments/link-relations/link-relations.xhtml) to choose appropriate "rel" properties for the links. When there are a large number of references and/or no link relation is appropriate, add a JSON array to the resource document. In these sub-elements of the array, include the most essential properties and provide a link with a _self_ "rel" that points to the complete document.

**Comment by fterpstra** [comment]
From discussion on 5-2-2021: We agree with the principle to link resources, we would suggest that the use of links as described by Jeff is an example. resulting in the text below:

Principle #XX – Make resources discoverable

To support [FAIR](https://www.go-fair.org/) principles, discoverability is key (it is one option to address the F in FAIR). When a resource has other resources associated with it, make the associated resources discoverable. 

For example through links in the document for that resource. Populate link elements and use link relations to choose appropriate "rel" properties for the links. When there are a large number of references and/or no link relation is appropriate, make the resource an array of other sub-resources. In these sub-recources of the array, include the most essential properties and provide a link with a self "rel" that points to the complete document. Another alternative is a URL template, see principle #4.
