### ISSUE TITLE
Reorganize Principles 7 and 8

### ISSUE THREAD

**Issue by jyutzler** [opengeospatial/OGC-Web-API-Guidelines#43]
### Principle #7 – Make Responses Clear

Use HTTP Status Codes from RFC7231 to indicate the results of the request. Since more than 70 status codes exist, reduce the use in your API to the most important ones. For example: 

TABLE

Response documents should reflect the status codes. 4XX responses indicate that the client is in error so the response should indicate what is wrong with the request. 5XX responses indicate that the server is in error so the response should include contact information. Since debugging information for server problems is not actionable by the client, it should be logged and not returned in the response document.

_Principle 8 goes away. See #38 for a candidate replacement._

**Comment by fterpstra** [comment]
Discussion from web api guidelines telecon 22-01-2021: the current text mentions "Be explicit which 30x statucs code your API supports. For any supported 30x follow the HTTP semantics." The list is an example list not exhaustive.
