### ISSUE TITLE
Rewrite Principle #17 (geospatial relations -> geospatial elements)

### ISSUE THREAD

**Issue by jyutzler** [opengeospatial/OGC-Web-API-Guidelines#44]
### Principle #17 – Follow OGC Guidelines regarding geospatial elements

* Provide SRSs with all coordinates.
* Where possible, explicitly name coordinates instead of relying on coordinate order. When this is not possible, follow the OGC Axis Order Policy.
* When needed, use WKT2 to describe SRSs. (from #37)
* Use explicit geospatial relations. (as in the existing Principle 17)

**Comment by fterpstra** [comment]
discussed in web api guidelinse telecon 22-01-2021. The principle makes spatial relations explicit while the pull requests adds information on implicit relations that can be extracted from coordinates. Therefor this information on SRSs etc should not be added to principle 17. Maybe we should be more clear on the use of relations and not limit it to geospatial relations. It should apply to all relations. perhaps we should change the title and take the word geospatial out.
Discussed on 5-2-2021: The more specific guidelines are the less valuable they become. We would argue to not refine the guidelines in the way suggested here.
