### ISSUE TITLE
URIs and link references should be predictable

### ISSUE THREAD

**Issue by jyutzler** [opengeospatial/OGC-Web-API-Guidelines#45]
It should be deterministic what document is going to be returned when a URI is opened. 

### Principle #XX – Make documents predictable
Make the document type of all resources predictable so that there is no ambiguity in how the client is supposed to parse the document. This applies to resources accessible through both a URI pattern (see Principle #4) and through a link (see #38).

**Comment by fterpstra** [comment]
From discussion on 5th february: We already use of HTTP content negotiation and IANA types. There is no "main stream IT" solution available addressing schema use that we are aware of. We will keep this issue open and monitor progress in this area.

**Comment by fterpstra** [comment]
Further discussion on feb 12th: Other than content negotiation and MIME type there is no foreseeable solution. reccomendation to close this issue. Such that we have no open (potentially unresolvable) issues when we convert this into a stable version(release) that can be referenced from an OGC policy.
