### ISSUE TITLE
Reference to obsolete RFC 2616

### ISSUE THREAD

**Issue by heidivanparys** [opengeospatial/OGC-Web-API-Guidelines#49]
The guidelines refer to RFC 2616, but that RFC has been obsoleted by RFC 7230, RFC 7231, RFC 7232, RFC 7233, RFC 7234, RFC 7235, see also https://www.rfc-editor.org/info/rfc2616 . The references to RFC 2616 should be replaced by the appropriate RFC from the aforementioned list. E.g. RFC 7231 for HTTP methods.

**Comment by ogcscotts** [comment]
@heidivanparys RFC 2616, correct?

**Comment by heidivanparys** [comment]
@ogcscotts RFC 2616 indeed, I updated the issue to reflect that.

**Comment by fterpstra** [comment]
We will update to 7231, if we find anything missing from 7231 we will add an extra reference
