### ISSUE TITLE
Metadata - Guideline 13

### ISSUE THREAD

**Issue by cmheazel** [opengeospatial/OGC-Web-API-Guidelines#52]
This guideline calls for metadata to be a part of the resource tree (a path element). In practice, we are associating metadata with resources though an association. Most notable, the `service-meta` and `data-meta` association types. This is a more flexible, and arguably more intuitive approach than that prescribed in Guideline 13.

**Comment by fterpstra** [comment]
The current guideline #13 is too strict, there are cases where explicitly putting meta-data in the resource path is confusing to the user/programmer. The guideline should be relaxed to state that you should provide meta-data. It should be there to help the client/user/programmer understand the API and its content. The metadata should be associated with the resource it describes. The service-meta and data-meta association types can be referenced as an example on how to do this.
