### ISSUE TITLE
Resolve comments from Carl Reed

### ISSUE THREAD

**Issue by cmheazel** [opengeospatial/OGC-Web-API-Guidelines#57]
Carl submitted comments as red-lines to a Word version of the API Guidelines document.  It can be found in the Comments folder.

**Comment by securedimensions** [comment]
The attached file make further proposals how to incorporate Carl's comments.
[OGC Web API Guidelines Reed edits and comments - AM.docx](https://github.com/opengeospatial/OGC-Web-API-Guidelines/files/6049128/OGC.Web.API.Guidelines.Reed.edits.and.comments.-.AM.docx)

**Comment by fterpstra** [comment]
On carl reeds comment on sorting: in the Dutch API Design rules we considered including a principle on this. It did not make it into the first normative standard as we could not get consensus on this. There is not a generally agreed upon best practice for this. our orginal proposal can be found here https://geonovum.github.io/KP-APIs/API-strategie-extensies/#sorting

**Comment by securedimensions** [comment]
Merged into master
