### ISSUE TITLE
Principle #4 – Use CRUD

### ISSUE THREAD

**Issue by cmheazel** [opengeospatial/OGC-Web-API-Guidelines#6]
• Allow CRUD Create, Read, Update, Delete, and Execute
• Allow HTTP methods that operate on resources; GET, POST, PUT, DELETE
• Also support HTTP communications methods
– HEAD to return HTTP Headers with no payload
– OPTIONS to support CORS

**Comment by cportele** [comment]
> Allow CRUD operations: Create, Read, Update, Delete, and Execute

What is meant by this? What is supported or not for a resource depends on the intended use. I suggest to simply delete this and change the name of the principle to something like "Be consistent with HTTP" or similar.

If it is deleted, the following is irrelevant: Why is "Execute" included, it is CRUD not CRUDE...

**Comment by ghobona** [comment]
How about this?

- If you allow CRUD Create, Read, Update, Delete operations, then it is recommended that you use HTTP methods GET, POST, PUT, and DELETE to operate on resources. This is only a recommendation and not a requirement.

**Comment by securedimensions** [comment]
addressed by principle no. 5 (HTTP) and 14 (Security)
