### ISSUE TITLE
Principle #5 – Don’t mix Singular and Plural

### ISSUE THREAD

**Issue by cmheazel** [opengeospatial/OGC-Web-API-Guidelines#7]
• It doesn’t matter if you use Singular or Plural for your nouns to build the path. But, don’t mix!
• Use concrete names to build the path
• /v1/<kind>/<type>
• kinds using plural := {features, maps, tiles, coverages, observations, processes, facts, ...}
• kinds using singular := {feature, map, tile, coverage, observation, process, fact, …}
• E.g. using plural
– POST /v1/features/tiger_roads/
– PUT /v1/maps/green_spaces/area51
– GET /v1/tiles/water_ways/4326/0/0

**Comment by joanma747** [comment]
Hi,
This might seem a silly discussion but there could be a technical reason for having a rule on this. If I understood correctly OpenAPI, each parameter in the URI template is defined as "path" or as "query" depending on if it will be before of after the "?". If it cannot be both he could have a problem (first we have to confirm that it cannot be both; but I suspect it cannot).

My suggestion is to use singular for the "path" and plural for the "query". This will allow the following notation:

http://server.bob/collection/buildings (for retrieving the full collection of "buildings")
and this:
http://server.bob?collections=buildings,roads (for retrieving buildings and road in the same response).

In any case, other solutions are possible without having to playing with the plural. This URI also fixes the issue:
http://server.bob/collections?id=buildings,roads

My two cents.

**Comment by cmheazel** [comment]
This best practice shows up in other best practices for APIs that I have seen.  It seems to have general support.  The principle applies to the path.  If the path resolves to more than one resource, then it should be plural.  You may want to use a query to select specific members.  If it resolves to a single resource, then it is singular.  A singular path would not need a query.

**Comment by cportele** [comment]
This really only applies to resources that are collections of other resources, but not for other cases. Some examples:

* `/collections/buildings/map` where `map` returns a rendered image of the features in `buildings`
* `/collections/buildings/schema` where `schema` returns a schema for the features in `buildings`
* `/collections/buildings/items/1234/name` where `name` returns a property value of a feature

I suggest to remove this principle or maybe change it to using plural for resources that are collections.

**Comment by ghobona** [comment]
I agree with "using plural for resources that are collections".

How about changing to this?

• Use plural for resources that are collections
• kinds using plural := {features, maps, tiles, coverages, observations, processes, facts, ...}
• kinds using singular := {feature, map, tile, coverage, observation, process, fact, …}
• e.g. using plural
• /collections/buildings/map where map returns a rendered image of the features in buildings
• /collections/buildings/schema where schema returns a schema for the features in buildings
• /collections/buildings/items/1234/name where name returns a property value of a feature

**Comment by securedimensions** [comment]
now addressed in master
