### ISSUE TITLE
Principle #6 – Put Complexity behind the ‘?’

### ISSUE THREAD

**Issue by cmheazel** [opengeospatial/OGC-Web-API-Guidelines#8]
• This where the fun begins 
• query-string parameters should be used to select a resource(s) based on the(ir) characteristics
– /v1/features/highways?id=A8 => returns highway A8
– /v1/features/highways?id=A8,A9 => returns highways A8 and A9
• But what if you select on a resource instance?
– /v1/features/highways/A8?id=A8
should that return true or the resource?
– /v1/features/highways/A8?id=A81
should that return false or null?
• Use of the query string to select resources is highly domain specific and must be described on a case to case basis

**Comment by cportele** [comment]
I do not understand what this principle is trying to say. How can the path "be identical regardless of the kind of resource"? What is meant by "domain specific aspects"? Etc. I suggest to remove this principle. Or rewrite to clarify what is meant.

**Comment by securedimensions** [comment]
now addressed in master
