### ISSUE TITLE
Principle #7 – Error Handling

### ISSUE THREAD

**Issue by cmheazel** [opengeospatial/OGC-Web-API-Guidelines#9]
• Error Codes are the developers insight into your API
– So be precise and as detailed as possible
• Usually, errors are associated with HTTP status codes
• But, support a „switch off“ which always returns a status code 200 plus additional information in the response body
– e.g. ?suppress_response_codes=true
• Return detailed human readable error no. + description + information how to fix things + contact details
{ “developer_message”: “…“,
„user_message“: „...“,
„error_code“: „...“,
„contact_details“: „...“
}

**Comment by cportele** [comment]
> However, support a "switch off" that always returns a status code 200 plus additional (debug / insight) information in the response body

I do not think we should require that every path supports this. You only need this in certain cases (e.g. if you want to use JSONP). This has not come up in the WFS 3.0 development, for example.

**Comment by cportele** [comment]
Here is a link to the list of status codes that we considered the most relevant ones for WFS 3.0 Core.

https://cdn.rawgit.com/opengeospatial/WFS_FES/3.0.0-draft.1/docs/17-069.html#http_status_codes

**Comment by securedimensions** [comment]
now addressed in master
